[project]
name = "connecpy"
version = "1.0.0"
description = "Server and client lib for Connect Protocol"
authors = [
    { name = "Yasushi Itoh" }
]
dependencies = [
    "httpx",
    "protobuf",
    "starlette",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "black>=23.12.1",
    "grpcio-tools",
    "uvicorn>",
    "black>=23.12.1",
    "grpcio",
    "protobuf",
    "connecpy",
    "brotli_asgi",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/connecpy"]
